'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=v=>JSON.parse(JSON.stringify(v)), get=(o,p)=>p.split('.').reduce((v,k)=>v?.[k],o);
function put(o,p,v){const keys=p.split('.');let item=o;for(const key of keys.slice(0,-1))item=item[key]??={};item[keys.at(-1)]=v;}
let role='device',config={},saved={},dirty=false,latest={},network={},remote=null,modelData={},polling=false,reviewing=false,noticeTimer;
const isDevice=()=>role==='device'||remote!==null;
async function request(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}});let value;try{value=await r.json();}catch{throw Error('The app is restarting or is not reachable. It will reconnect automatically.');}if(!r.ok)throw Error(value.error||'The request could not be completed. Try again.');return value;}
const send=(path,value={},method='POST')=>request(path,{method,body:JSON.stringify(value)});
async function api(path,options={}){
  if(!remote)return request(path,options);
  const actions={'/api/config':options.method==='PUT'?'save':'get','/api/status':'status','/api/models':'models','/api/restart':'restart','/api/models/install':'install','/api/models/cancel':'cancel'};
  if(!actions[path])throw Error('Open the device app on that PC to change this setting.');
  return send('/api/devices/'+encodeURIComponent(remote.id)+'/manage',{action:actions[path],params:options.body?JSON.parse(options.body):{}});
}
const act=(path,value={},method='POST')=>api(path,{method,body:JSON.stringify(value)});
function notice(message,error=false){clearTimeout(noticeTimer);$('notice').hidden=false;$('notice').className=error?'error':'success';$('notice').textContent=message;if(!error)noticeTimer=setTimeout(()=>$('notice').hidden=true,6500);}
function attempt(fn){return async event=>{event?.preventDefault();try{await fn(event);}catch(e){notice(e.message,true);}};}
function changed(){dirty=JSON.stringify(config)!==JSON.stringify(saved);$('saveBar').hidden=!dirty;$('saveState').textContent='Unsaved changes';$('permissionState').textContent=dirty?'Unsaved — these changes are not active yet.':'Only applied settings are active. Saved changes may need a restart.';}
function syncFields(){for(const field of document.querySelectorAll('[data-field]')){const value=get(config,field.dataset.field);if(field.type==='checkbox')field.checked=value===true;else field.value=field.dataset.list?(Array.isArray(value)?value.join('\n'):''):(value??'');} $('rawConfig').value=JSON.stringify(config,null,2);renderEndpoints();changed();}
function wireFields(){for(const field of document.querySelectorAll('[data-field]'))field.oninput=()=>{let value=field.type==='checkbox'?field.checked:field.value;if(field.dataset.list)value=field.value.split(/\n/).map(s=>s.trim()).filter(Boolean).map(s=>field.dataset.list==='number'?Number(s):s);put(config,field.dataset.field,value);changed();};}
function visibility(){document.querySelectorAll('.device-only').forEach(e=>e.hidden=!isDevice());document.querySelectorAll('.eef-only').forEach(e=>e.hidden=isDevice());$('autoApply').closest('label').hidden=!isDevice();$('startup').disabled=!!remote;document.querySelectorAll('[data-page=network] .device-only input,[data-page=network] .device-only textarea,[data-page=network] .device-only button').forEach(e=>e.disabled=!!remote);for(const id of ['checkUpdate','applyUpdate'])$(id).disabled=!!remote;$('updateStatus').textContent=remote?'Check and install updates in that PC’s device app.':'';if($('remoteAllowed'))$('remoteAllowed').disabled=!!remote;$('brandRole').textContent=isDevice()?'Device app':'Your EEF network';$('appRole').textContent=remote?'MANAGING '+remote.name:(isDevice()?'THIS DEVICE':'YOUR NETWORK');}
function page(){const name=location.hash.slice(1)||'home',valid=['home','devices','models','permissions','network','settings','advanced'];const target=valid.includes(name)?name:'home';document.querySelectorAll('[data-page]').forEach(e=>e.hidden=e.dataset.page!==target);document.querySelectorAll('nav a').forEach(a=>a.setAttribute('aria-current',a.hash==='#'+target?'page':'false'));$('pageTitle').textContent=target[0].toUpperCase()+target.slice(1);if(target==='models')loadModels().catch(e=>notice(e.message,true));if(target==='advanced')$('rawConfig').value=JSON.stringify(config,null,2);}
const permissionGroups=[
 ['Files & apps',[
 ['filesystem.read','Read files','Only files inside your allowed folders.'],['filesystem.write','Modify files','Can create, change, or delete files in the allowed folders.',true],['process.enabled','Run approved programs','Only programs you explicitly add below.',true],['applications.enabled','Control apps','Can launch and close the apps you approve.',true]],
 [['permissions.filesystem.roots','Allowed folders — applies to reading and modifying','folder'],['permissions.process.allowed_executables','Approved programs','program'],['permissions.applications.allowed','Apps EEF may control','program']]],
 ['Network', [['http.enabled','Access websites and APIs','Only the sites you add below.']], [['permissions.http.allowed_hosts','Allowed sites (one domain per line)']]],
 ['Audio', [['media.microphone','Microphone','Can record audio when EEF requests it.',true],['media.audio_output','Speakers','Can play audio on this PC.'],['media.tts','Voice output','Read text aloud with the system voice.'],['stt.enabled','Speech recognition','Send audio to the speech service you choose.',true]], []],
 ['Camera & screen', [['media.camera','Camera','Can capture images from this PC’s camera.',true],['media.screen_capture','Screen','Can capture what is visible on your display.',true]], []],
 ['Input control', [['media.input_control','Keyboard & mouse','EEF may click, type, and interact with this computer.',true]], []],
 ['Device control', [['wake_on_lan.enabled','Wake other computers','Send a wake signal only to computers you approve.']], [['permissions.wake_on_lan.allowed_macs','Approved computers (hardware addresses)'],['permissions.wake_on_lan.broadcast_addresses','Your network’s broadcast addresses'],['permissions.wake_on_lan.ports','Wake signal ports','number']]]
];
function buildPermissions(){
 $('permissionGroups').innerHTML=permissionGroups.map(([name,permissions,lists])=>`<section class="panel"><h3>${esc(name)}</h3><div class="permission-grid">${permissions.map(([key,label,help,risk])=>`<div class="permission"><label class="toggle"><input type="checkbox" data-field="permissions.${key}">${esc(label)}</label><small class="${risk?'risk':''}">${esc(help)}</small></div>`).join('')}</div>${lists.map(([key,label,picker])=>`<label>${esc(label)}<textarea rows="3" data-field="${key}" data-list="${picker==='number'?'number':'text'}" placeholder="One item per line"></textarea></label>${['folder','program'].includes(picker)?`<button type="button" class="secondary" data-picker="${picker}" data-target="${key}">Choose ${picker}…</button>`:''}`).join('')}${name==='Audio'?'<label>Speech service<select id="speechService"><option value="compatible">Compatible speech service</option></select></label><label>Speech service address<input data-field="permissions.stt.endpoint" placeholder="Address supplied by your speech service"></label><label>Speech model<input data-field="permissions.stt.model"></label><label>Voice output<select disabled><option>System default voice</option></select></label><small>More provider options are available in Advanced.</small>':''}</section>`).join('');
 document.querySelectorAll('[data-picker]').forEach(button=>button.onclick=attempt(async()=>{if(remote)throw Error('Folder selection must happen on that PC. Enter its path here instead.');const p=await send('/api/pick',{kind:button.dataset.picker});if(p.path){const list=get(config,button.dataset.target)||[];put(config,button.dataset.target,[...new Set([...list,p.path])]);syncFields();}}));
}
function prettyCapability(id){return({'llm.infer':'Text AI','vlm.analyze':'Image understanding','system.info':'Device information','system.ping':'Connection checks','node.update':'Updates','node.configure':'Device settings','filesystem':'File access','process.exec':'Approved programs','application.control':'App control','launch_application':'App launching','http.request':'Web access','stt.transcribe':'Speech recognition','network.wol':'Wake computers','microphone.capture':'Microphone','audio.output':'Speakers','tts.speak':'Voice output','camera.capture':'Camera','screen.capture':'Screen','input.control':'Keyboard & mouse'})[id]||'Additional device service';}
function stateText(s){const c=s.connection||{},state=c.state;return({connected:['Connected','This PC is connected to EEF and can provide its enabled services.'],connecting:['Connecting','Signing this device in to EEF.'],retrying:['Reconnecting','EEF is not reachable. We are retrying in the background. Check that EEF is running and the network is available.'],disconnected:['Disconnected','The connection to EEF was lost. Retry or choose another EEF.'],waiting:['Waiting for EEF','Launch EEF on this PC to connect automatically, or add a connection code from another PC.'],starting:['Starting','Preparing this device’s services and selected models.'],error:['Needs attention','Device services could not start. Review the details below, then change settings or retry.']})[state]||['Offline','The app is not reachable. Launch it from the Start menu and try again.'];}
function card(title,body,extra=''){return `<article class="card ${extra}"><h3>${esc(title)}</h3>${body}</article>`;}
function stat(n,label){return `<p class="stat">${esc(n)}</p><p>${esc(label)}</p>`;}
function renderStatus(){
 const s=latest,d=isDevice(),devices=network.world?.devices||[],connected=devices.filter(n=>n.connected);
 let title,help;if(d){[title,help]=stateText(s);}else{title=connected.length?(s.models?.length?'Ready':'Connected — choose a model'):'Waiting for devices';help=connected.length?'EEF uses the devices and models shown below.':'Install and launch the device app on this PC. It will connect automatically.';}
 $('health').textContent=title;$('health').className='badge'+((d?s.connection?.state==='connected':connected.length)?'':' warn');$('homeTitle').textContent=title;$('homeHelp').textContent=help;$('deviceName').textContent=d?(s.name||config.name||'This PC'):'YOUR EEF NETWORK';$('version').textContent=`${d?'Device app':'EEF'} version ${s.version||'0.3.2'}`;
 $('homeActions').innerHTML=d?'<a class="button" href="#permissions">Choose permissions</a><a class="button secondary" href="#models">Choose models</a><a href="#network">Connection help</a>':'<a class="button" href="#devices">View devices</a><a class="button secondary" href="#network">Add a device</a>';
 if(d){const hw=s.hardware||{},enabled=Object.values(s.permissions||{}).flatMap(v=>Object.values(v||{})).filter(v=>v===true).length;
  const inventory=hw.devices||[]; $('hardwareAvailability').innerHTML='<h3>Detected hardware</h3>'+(hw.inventory_available?'<p>'+esc(inventory.length?inventory.map(item=>item.Name).join(' · '):'No camera, audio endpoint, or monitor was reported.')+'</p><small>Detection does not grant permission or prove capture will succeed. Windows privacy settings also apply. Device selection currently uses the system default.</small>':'<p>Hardware inventory is not available. Permissions below are preferences, not proof that a camera or microphone is ready.</p>');
  $('homeCards').innerHTML=card('This PC',`<p>${esc(hw.cpu_name||'Detecting processor…')}</p><p>${hw.ram_mb?esc((hw.ram_mb/1024).toFixed(1))+' GB memory':'Memory not reported'}</p><p>${esc(hw.gpu_model||'GPU details not reported; CPU models are available.')}</p>`)+card('Device permissions',stat(enabled,'Applied permission switches')+'<a href="#permissions">Manage permissions</a>')+card('AI models',stat(s.models?.length||0,'Models available to EEF')+'<a href="#models">Install or choose a model</a>');
  $('connectionTitle').textContent=title;$('connectionHelp').textContent=`${s.coordinator_name||config.coordinator_name||'EEF connection'} — ${help}`;$('connectionDetails').textContent=JSON.stringify(s.connection||{},null,2);$('activity').textContent=s.last_activity?prettyCapability(s.last_activity)+' — most recent request':'No requests yet. Once connected, this PC can help EEF with the services you enable.';
 }else{$('homeCards').innerHTML=card('Connected devices',stat(connected.length,'Online now'))+card('AI models',stat(s.models?.length||0,'Available across your devices'))+card('Network',`<p>${devices.length-connected.length} offline devices</p><p>${connected.length?'Serving connected devices':'No devices connected yet'}</p>`);const tasks=s.world?.active_tasks||[];$('activity').textContent=tasks.length?tasks.slice(-5).map(t=>`${t.description||'Network task'} — ${t.status||'In progress'}`).join('\n'):'No tasks yet.';}
 $('chatPanel').hidden=d;$('restartBanner').hidden=!s.pending_restart;$('diagnostics').textContent=JSON.stringify({version:s.version,status:s,remote_device:remote?.id},null,2);
 if(!d||role==='eef')renderDevices(devices);else $('devices').innerHTML=card(s.name||'This PC',`<p>${esc(title)}</p><p>Run EEF to see all devices in your network.</p>`);
 if(s.proposal_pending&&!reviewing){$('proposalBanner').hidden=false;}else $('proposalBanner').hidden=true;
 renderProgress(s.download);
}
function renderDevices(devices){$('devices').innerHTML=devices.length?devices.map(n=>card(n.name||'Device',`<p><span class="badge ${n.connected?'':'offline'}">${n.connected?'Connected':'Offline'}</span></p><p>${n.connected?'Available to EEF':'Last seen '+(n.last_seen_ms?new Date(n.last_seen_ms).toLocaleString():'before this session')}</p><p>${esc((n.capabilities||[]).map(prettyCapability).filter((v,i,a)=>a.indexOf(v)===i).join(' · '))}</p><button data-manage="${esc(n.node_id)}" ${n.connected?'':'disabled'}>Configure device</button><details><summary>Device details</summary><p>${esc(n.node_id)}</p></details>`,n.connected?'':'offline')).join(''):'<article class="card"><h3>No devices connected yet</h3><p>Install and launch the device app on this PC or another computer.</p><a class="button" href="#network">Add device</a></article>';document.querySelectorAll('[data-manage]').forEach(b=>b.onclick=attempt(async()=>{if(dirty&&!confirm('Discard your unsaved changes?'))return;const n=devices.find(n=>n.node_id===b.dataset.manage);remote={id:n.node_id,name:n.name};await loadConfig();visibility();$('remoteBanner').hidden=false;$('remoteName').textContent='Managing '+n.name;location.hash='permissions';await poll();}));}
function renderEndpoints(){const list=config.endpoints||[];$('endpoints').innerHTML=list.map((e,i)=>`<div class="endpoint"><label>EEF address<input data-endpoint="${i}" value="${esc(typeof e==='string'?e:e.address)}"></label><label>Priority<input data-priority="${i}" type="number" value="${esc(e.priority||0)}"></label><button data-remove-endpoint="${i}" class="secondary">Remove</button></div>`).join('');document.querySelectorAll('[data-endpoint],[data-priority]').forEach(f=>f.oninput=()=>{const index=Number(f.dataset.endpoint??f.dataset.priority);if(typeof config.endpoints[index]==='string')config.endpoints[index]={address:config.endpoints[index],priority:0};config.endpoints[index][f.dataset.endpoint!==undefined?'address':'priority']=f.dataset.endpoint!==undefined?f.value:Number(f.value);config.auto_local=false;config.local_pairing=false;changed();});document.querySelectorAll('[data-remove-endpoint]').forEach(b=>b.onclick=()=>{config.endpoints.splice(Number(b.dataset.removeEndpoint),1);renderEndpoints();changed();});}
async function loadConfig(){const c=await api('/api/config');config=c.config;saved=clone(config);syncFields();}
async function save(restartAfter=false){const result=await act('/api/config',{config},'PUT');if(result.approval_required){notice('Changes sent. Review and approve them in that PC’s device app.');saved=clone(config);changed();return;}saved=clone(config);changed();latest.pending_restart=true;$('restartBanner').hidden=false;if(reviewing&&!remote){await request('/api/proposal',{method:'DELETE'});reviewing=false;}notice('Changes saved. Restart to apply them.');if(restartAfter||$('autoApply').checked)await restartNow();}
async function restartNow(){if(dirty)throw Error('Save or discard your edits before restarting.');if(!isDevice()&&!confirm('Restart EEF? Connected devices will reconnect; running tasks may be interrupted.'))return;await act('/api/restart');notice(isDevice()?'Restarting device services. The connection will return automatically.':'Restarting EEF. Devices will reconnect automatically.');$('restartBanner').hidden=true;}
const gb=bytes=>Number(bytes||0)>=1e9?(Number(bytes)/1e9).toFixed(1)+' GB':Math.round(Number(bytes||0)/1e6)+' MB';
function renderProgress(job){if(!job||job.state==='idle'){$('modelProgress').hidden=true;return;}$('modelProgress').hidden=false;const percent=job.total?Math.min(100,Math.round(100*job.completed/job.total)):0;$('modelProgress').innerHTML=`<strong>${esc(job.name||'Model')}: ${esc(job.state==='installed'?'Installed — choose Use model below':job.state==='error'?job.error:'Downloading'+(job.total?' '+percent+'%':''))}</strong>${job.state==='downloading'?`<progress max="100" ${job.total?'value="'+percent+'"':''} aria-label="Model download progress"></progress><button id="cancelDownload" class="secondary">Cancel download</button>`:''}`;if($('cancelDownload'))$('cancelDownload').onclick=attempt(()=>act('/api/models/cancel'));}
async function loadModels(){if(!isDevice()){$('modelHelp').textContent='Models run on your devices. Configure a device to install or choose its models.';$('models').innerHTML=(network.models||[]).map(m=>card(m.model_id||m.name||'Model',`<p>${esc(m.modality==='vlm'?'Text and images':'Text')}</p><p>Device: ${esc((network.world?.devices||[]).find(n=>n.node_id===m.node_id)?.name||'Connected device')}</p><p>Ready on the connected device</p>`)).join('')||card('No AI models available','<p>Open Devices, choose Configure device, then Models.</p><a href="#devices">Choose a device</a>');return;}
 modelData=await api('/api/models');$('modelHelp').textContent=modelData.backend==='ollama'?'Using the model service already on this PC. Choose which installed models EEF may use.':'Using the included model runtime. Download a model below or choose an existing file.';renderProgress(modelData.download);renderModelCards();renderCatalog();}
function renderModelCards(){const ollama=modelData.backend==='ollama';const selected=ollama?get(config,'models.ollama.selected')||[]:get(config,'models.llamacpp.slots')||[];const items=ollama?(modelData.ollama_models||[]):[...(modelData.installed||[]),...selected.filter(s=>!(modelData.installed||[]).some(m=>m.id===s.model_id)).map(s=>({id:s.model_id,name:s.model_id,path:s.model_path,source:'Your local model file'}))];
 $('models').innerHTML=items.map((m,i)=>{const id=ollama?m.name:m.id,chosen=selected.some(s=>s.model_id===id);return card(m.name||id,`<p>${esc(ollama?'Existing model service':m.source||'Local file')} · ${gb(m.size||m.bytes)}</p><p>${chosen?'Selected'+(dirty?' — unsaved':latest.pending_restart?' — restart required':''):'Installed, not selected'}</p><button data-use-model="${i}" ${chosen?'disabled':''}>${chosen?'Selected':'Use model'}</button>${chosen?` <button class="secondary" data-disable-model="${esc(id)}">Stop using</button>`:''}`);}).join('')||card('No installed models','<p>Choose a model below to get started. Downloads happen only when you request them.</p>');
 for(const b of document.querySelectorAll('[data-use-model]'))b.onclick=attempt(async()=>{const m=items[Number(b.dataset.useModel)];if(ollama){const list=get(config,'models.ollama.selected')||[];put(config,'models.ollama.selected',[...list,{model_id:m.name,modality:'text'}]);}else selectLocal(m.id,m.path);changed();renderModelCards();notice('Model selected. Apply and restart to make it available to EEF.');});
 for(const b of document.querySelectorAll('[data-disable-model]'))b.onclick=()=>{const path=ollama?'models.ollama.selected':'models.llamacpp.slots';put(config,path,(get(config,path)||[]).filter(m=>m.model_id!==b.dataset.disableModel));changed();renderModelCards();};
}
function selectLocal(name,path){if(!name.trim()||!path.trim())throw Error('Choose a model file and give it a name.');const slots=get(config,'models.llamacpp.slots')||[];if(slots.some(s=>s.model_id===name))throw Error('That model is already selected.');let port=8082;while(slots.some(s=>s.port===port))port++;put(config,'models.provider','llamacpp');put(config,'models.llamacpp.slots',[...slots,{model_id:name,model_path:path,port,context:2048,gpu_layers:0}]);syncFields();}
function renderCatalog(){const search=$('modelSearch').value.toLowerCase();$('catalog').innerHTML=(modelData.catalog||[]).filter(m=>`${m.name} ${m.description}`.toLowerCase().includes(search)).map(m=>{const ram=Number(latest.hardware?.ram_mb||0)/1024,low=ram>0&&ram<m.recommended_ram_gb;return card(m.name,`<p>${esc(m.description)}</p><p>${gb(m.bytes)} download · about ${esc(m.recommended_ram_gb||'?')} GB RAM recommended</p><p>${esc(m.source)} · ${esc(m.license||'See model source')}</p>${low?'<p class="risk">This PC has less memory than recommended. Choose a smaller model if it does not start.</p>':''}<button data-install="${esc(m.id)}">Install model</button>`);}).join('');document.querySelectorAll('[data-install]').forEach(b=>b.onclick=attempt(async()=>{await act('/api/models/install',{id:b.dataset.install});notice('Download started. This does not select the model automatically.');await loadModels();}));}
async function poll(){if(polling)return;polling=true;try{if(role==='eef')network=await request('/api/status');latest=remote||role==='device'?await api('/api/status'):network;renderStatus();}catch(e){$('health').textContent='Offline';$('health').className='badge offline';$('homeTitle').textContent='App is not reachable';$('homeHelp').textContent='If the app is restarting, this page will reconnect automatically. Otherwise, launch it from the Start menu.';}finally{polling=false;}}
async function init(){const ui=await request('/api/ui');role=ui.role;buildPermissions();wireFields();$('nav').innerHTML=['Home','Devices','Models','Permissions','Network','Settings','Advanced'].map(s=>`<a href="#${s.toLowerCase()}">${s}</a>`).join('');
 $('content').insertAdjacentHTML('afterbegin','<div id="remoteBanner" class="banner" hidden><strong id="remoteName"></strong><button id="backToEEF" class="secondary">Back to EEF</button></div><div id="proposalBanner" class="banner" hidden><strong>EEF has requested changes to this device.</strong><button id="reviewProposal">Review changes</button><button id="rejectProposal" class="secondary">Reject</button></div>');
 $('backToEEF').onclick=attempt(async()=>{if(dirty&&!confirm('Discard unsaved edits?'))return;remote=null;$('remoteBanner').hidden=true;await loadConfig();visibility();await poll();location.hash='devices';});
 $('reviewProposal').onclick=attempt(async()=>{if(dirty&&!confirm('Replace unsaved edits with the proposed settings?'))return;config=(await request('/api/proposal')).config;reviewing=true;syncFields();location.hash='permissions';notice('Review the proposed permissions, models, and settings. Save only if you approve.');});$('rejectProposal').onclick=attempt(async()=>{await request('/api/proposal',{method:'DELETE'});reviewing=false;await poll();});
 const settings=document.querySelector('[data-page=settings]');settings.insertAdjacentHTML('afterbegin','<section class="panel device-only"><h2>Management from EEF</h2><label class="toggle"><input type="checkbox" data-field="management.allow_remote" id="remoteAllowed"> Allow EEF to apply settings and restart this device</label><p class="risk">Enable only for a trusted EEF network. Otherwise, changes requested from EEF need your approval here. This permission can only be granted in the local device app.</p></section>');wireFields();
 await loadConfig();visibility();for(const a of document.querySelectorAll('.peer'))a.href=ui.peer_url||'#devices';
 $('autoApply').checked=localStorage.getItem('eef.autoApply')==='true';$('autoApply').onchange=()=>localStorage.setItem('eef.autoApply',String($('autoApply').checked));
 const startup=await request('/api/startup').catch(()=>({supported:false}));$('startup').checked=startup.enabled;$('startup').disabled=!startup.supported;$('startupLabel').textContent=`Start ${role==='device'?'the device app':'EEF'} automatically when I sign in`;
 $('startup').onchange=attempt(async()=>{if(remote)throw Error('Change startup in the local device app.');try{await send('/api/startup',{enabled:$('startup').checked},'PUT');notice('Startup preference saved.');}catch(e){$('startup').checked=!$('startup').checked;throw e;}});
 $('save').onclick=attempt(()=>save());$('saveRestart').onclick=attempt(()=>save(true));$('discard').onclick=()=>{config=clone(saved);syncFields();};$('refresh').onclick=attempt(poll);$('refreshModels').onclick=attempt(loadModels);$('modelSearch').oninput=renderCatalog;
 document.querySelectorAll('[data-action=restart]').forEach(b=>b.onclick=attempt(restartNow));$('later').onclick=()=>{$('restartBanner').hidden=true;notice('Saved settings will apply after the next restart.');};
 $('useLocal').onclick=attempt(async()=>{if(dirty&&!confirm('Discard unsaved changes and connect to local EEF?'))return;await act('/api/network/local');await loadConfig();notice('Looking for EEF on this PC. Launch EEF if it is not running.');});
 $('createInvite').onclick=attempt(async()=>{const v=await send('/api/network/invite');$('inviteLabel').hidden=false;$('inviteOutput').value=v.code;$('inviteOutput').select();notice('Keep this connection code private. Paste it in the other PC’s device app.');});
 $('join').onclick=attempt(async()=>{let v;try{v=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob($('inviteInput').value.trim()),c=>c.charCodeAt(0))));}catch{throw Error('This connection code is not valid. Copy it again from EEF.');}if(typeof v.address!=='string'||typeof v.psk!=='string'||v.psk.length<12)throw Error('This connection code is incomplete.');config.endpoints=[{address:v.address,priority:100}];config.psk=v.psk;config.coordinator_name=v.name||'EEF';config.auto_local=false;config.local_pairing=false;syncFields();await save(true);$('inviteInput').value='';});
 $('addEndpoint').onclick=()=>{config.endpoints??=[];config.endpoints.push({address:'',priority:0});renderEndpoints();changed();};
 $('installCustom').onclick=attempt(async()=>{await act('/api/models/install',{id:$('customModel').value.trim()});await loadModels();});$('pickModel').onclick=attempt(async()=>{$('modelPath').value=(await act('/api/pick',{kind:'model'})).path;});$('addLocalModel').onclick=attempt(async()=>{selectLocal($('localModelName').value,$('modelPath').value);changed();notice('Model selected. Apply and restart when ready.');});
 $('applyRaw').onclick=attempt(async()=>{const value=JSON.parse($('rawConfig').value);if(!value||Array.isArray(value)||typeof value!=='object')throw Error('Configuration must be an object.');config=value;syncFields();notice('Edits loaded. Save to validate and apply them.');});
 $('restore').onclick=attempt(async()=>{if(confirm('Restore the previous saved configuration? Unsaved edits will be discarded.')){await act('/api/config/restore');await loadConfig();latest.pending_restart=true;$('restartBanner').hidden=false;}});
 $('reset').onclick=attempt(async()=>{if(confirm('Reset this device’s settings? Permissions will be disabled. Your device ID and downloaded models stay intact.')){await act('/api/config/reset');await loadConfig();latest.pending_restart=true;$('restartBanner').hidden=false;}});
 $('checkUpdate').onclick=attempt(async()=>{$('updateStatus').textContent='Checking for updates…';const u=await act('/api/update/check');$('updateStatus').textContent=u.update_available?'Version '+u.latest_version+' is available.':'You are up to date.';});$('applyUpdate').onclick=attempt(async()=>{if(dirty)throw Error('Save or discard your edits before installing an update.');const check=await act('/api/update/check');if(!check.update_available){$('updateStatus').textContent='You are up to date.';return;}if(confirm('Download and install version '+check.latest_version+'?')){$('applyUpdate').disabled=true;try{$('updateStatus').textContent='Downloading and verifying the update…';await act('/api/update/apply');latest.pending_restart=true;$('restartBanner').hidden=false;$('updateStatus').textContent='Update installed. Restart now to use it.';notice('Update installed. Use Restart now to apply it.');}finally{$('applyUpdate').disabled=false;}}});
 $('chatForm').onsubmit=attempt(async()=>{$('reply').textContent='Working…';const value=await send('/api/chat',{message:$('message').value});$('reply').textContent=value.reply||'Request completed.';});
 $('exportDiagnostics').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:latest.version,connection:latest.connection,hardware:latest.hardware,capabilities:latest.capabilities},null,2)],{type:'application/json'}));a.download='eef-diagnostics.json';a.click();URL.revokeObjectURL(a.href);};
 addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});addEventListener('hashchange',page);page();await poll();setInterval(poll,3000);setInterval(()=>{if(location.hash==='#models')loadModels().catch(()=>{});},6000);
}
init().catch(e=>notice(e.message,true));
